name: Publish BrigadiKt
concurrency:
  group: ${{ github.workflow }}
on: [workflow_dispatch]
jobs:
  publish:
    runs-on: macos-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Configure version
        id: calver
        run: echo "VERSION=$(date -u +'%Y.%-m')-$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV

      - name: Publish package
        run: ./gradlew publish --stacktrace
        env:
          FRUXZ_DEV_USER: ${{ secrets.FRUXZ_DEV_USER }}
          FRUXZ_DEV_SECRET: ${{ secrets.FRUXZ_DEV_SECRET }}
          GH_RELEASE_VERSION: ${{ env.VERSION }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: ${{ github.actor }}

      - name: Create GitHub Release
        uses: elgohr/Github-Release-Action@v5
        with:
          tag: ${{ env.VERSION }}
          title: ${{ env.VERSION }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}